### ISSUE TITLE
“Considered GPL”

### ISSUE THREAD

**Issue by Rarst** [Ipstenu/wporg-plugin-guidelines#10]
> Without a license.txt file, or referencing and/or declaring a license within code comments or a readme.txt file, the plugin and all its components are considered GPLv2 or later.

> https://github.com/Ipstenu/wporg-plugin-guidelines/blob/master/guideline-02.md

Repository has no power to “consider” licenses upon third party code.

It can, of course, set and enforce license rules.

However _assuming_ licenses is baseless practice, which is dangerous to downstream consumers. 

Repository **cannot** promise that what I download is GPLv2+ if **its developer did not make it so**.

Repository **can** remove code for non–compliance, but it **cannot** make licensing decisions about it. Only developer / copyright holder can.

**Comment by Otto42** [comment]
These are guidelines for developers. This is our way to tell them that only GPLv2+ code is allowed in the repository, and by uploading to the repository, they agree that it is. If they upload non-GPL-Compatible code, then we'll remove it and shut down their plugin.

We're not "assuming" anything. This guideline states, flat out, what our rules for uploading code are. If you don't agree to these guidelines, then you are not permitted to put your code in the WordPress plugin directory.

**Comment by Ipstenu** [comment]
Would it be more clear if the guideline was "Include a license in your plugin with a license.txt file (or accept GPLv2 or later as your default)" instead?

> Without a license.txt file, or referencing and/or declaring a license within code comments or a readme.txt file, the plugin developer is confirming that all its components are GPLv2 or later.

I don't want to repeat Item 1 again (which says "everything has to be GPL") but this is basically a 1b corollary, if you don't pick a license, you're accepting the default. Everything has to have a license, and short of punting out everyone who didn't declare it (which we certainly could do...) this offers a bit of protection.

**Comment by Rarst** [comment]
> This is our way to tell them that only GPLv2+ code is allowed in the repository, and by uploading to the repository, they agree that it is.

It is very confusing and problematic way to express this thought.

>  If they upload non-GPL-Compatible code, then we'll remove it and shut down their plugin.

Then make it say **this**. Simple and clear, no presumptions.

>  if you don't pick a license, you're accepting the default

This is just not how licensing things work. What if I upload code someone _else_ wrote? I am in no place to accept anything about it either.

As above if the intent is “comply or get removed” then that is what rule should say. “If you don't explicitly comply we are going to do some creative guesswork” is dangerous way to put it.

**Comment by Ipstenu** [comment]
We're arguing different sides. It's not that we're saying "Licensing means if you don't declare..."

We're saying our Terms of Use say "If you don't specify, then by default ..." It's a user agreement, between the developer and the directory as a service. If you don't upload code you don't have the rights to accept/declare licenses for, then you've already violated the first guideline (all code must be GPL).

Perhaps it would be better to re-do this as

> 2. By uploading your plugin, you confirm you have the legal rights/permissions to do so.
>
> Plugins may only contain files that the developer has the right to upload, and the users have the right to use. If, for example, a contract states the code will not be publicly released, then it cannot be hosted on the Directory. Similarly, if there is no way to validate the licensing of a plugin's code and confirm it is GPL compliant, it cannot be included.

**Comment by Rarst** [comment]
User agreement is not a replacement for software licensing process.

> 2. Include a license in your plugin with a license.txt file.

> Without a license.txt file, or referencing and/or declaring a license within code comments or a readme.txt file, the plugin **is not in compliance with licensing guidelines and will be removed**.

**Comment by Ipstenu** [comment]
Since the intro already says plugins will be removed for guideline violations, and guideline 1 already says it has to be GPL, is there a problem with removing this altogether and replacing it with one that covers the other intent which is to prevent people from uploading code they don't have the right to do?

We can (easily) add a clause to guideline 1 - https://github.com/Ipstenu/wporg-plugin-guidelines/blob/master/guideline-01.md - that says "Plugins must declare a license and be compatible with..."

Done. Now this guideline becomes redundant. Or am I missing something else in your point, Rarst?

**Comment by Rarst** [comment]
> We can (easily) add a clause to guideline 1 - that says "Plugins must declare a license and be compatible with..."

That would work fine.

> Done. Now this guideline becomes redundant. Or am I missing something else in your point, Rarst?

Agreed. My only point here is that "default" clause is problematic and unnecessary.

**Comment by Ipstenu** [comment]
Alrighty - can folks weigh in on https://github.com/Ipstenu/wporg-plugin-guidelines/pull/14 ? :)

**Comment by laralfield** [comment]
Is it not true that the downstream aspect of the GPL requires that any derivative of GPL code also must be licensed under the original GPL version or later? This would include any plugin for WordPress, solving the issue from a fundamental legal standpoint, a long time before submission.

**Comment by Rarst** [comment]
> Is it not true that the downstream aspect of the GPL requires that any derivative of GPL code also must be licensed under the original GPL version or later? This would include any plugin for WordPress, solving the issue from a fundamental legal standpoint, a long time before submission.

Repository allows GPL–compatible, but non–GPL plugins (such as MIT and other licensed).

**Comment by Ipstenu** [comment]
@laralfield - For some reason, I can't see your comment but it emailed me (whaaaa?)

I don't want to get into the GPL inheritance debate ;) BUT. Probably yes (currently yes). Thankfully yes or no it doesn't matter here. We require (not allow) code to be GPLv2 (or later) compatible, which does include MIT etc.

The issue at heart is 'do we have the ability to say if you DON'T specify a license, we assume it's GPL' and ... yeah, no. So even though we've been saying it that way for years, we're going to say it a different way. All code must be compatible, and declare.

I'll ask Dion or someone if we can scan all readme.txt files for no license declarations ... Yikes.

**Comment by Otto42** [comment]
> What if I upload code someone else wrote?

The intent here is to put that onus on the plugin author (the person uploading the code). It's their responsibility to ensure license compatibility, and to only upload code that is acceptable for the directory. 

We're assuming they do that. We're assuming that any code they upload is GPL-compatible. That's what we're trying to convey with these two guidelines. That's why it's two guidelines instead of just one: to make it really, really clear. GPL-compatible only. 

I don't think that requiring them to explicitly state licenses is a replacement for this. That just means they'll slap a "GPL" label on whatever they upload and consider the matter closed, and it puts onus on us to do the checking that they should have done in the first place. 

The main things that need to be conveyed:

- GPLv2+ compatible.
- You're responsible for what you upload.
- Make damn sure that it's compatible because that's the assumption we're going to make by default.

However you want to convey that is fine by me.

**Comment by Ipstenu** [comment]
* GPLv2+ compatible.

I think G1 covers this

* You're responsible for what you upload.

That's what I'm hoping to do in G2 2.0.

* Make damn sure that it's compatible because that's the assumption we're going to make by default.

Again G1 covers this.
