### ISSUE TITLE
"Ad" vs "Adverts"

### ISSUE THREAD

**Issue by GaryJones** [Ipstenu/wporg-plugin-guidelines#19]
There are a few instances of "ad" or "ads" as abbreviated forms of "advert" or "adverts"/"advertisements", at least in 11 and 12, though may be in other guidelines too. There are also instances of the non-abbreviated versions of those words too.

Would it make sense for them all to be consistent? The longer word may be easier to translate into other languages if needed, and removes a colloquialism.

**Comment by Ipstenu** [comment]
It would. Good call. I patched some and one bit is waiting on the consensus for the upsell clarifications.

**Comment by GaryJones** [comment]
There's another instance of "ads" in the paragraph in the upsell branch in G11 (which might be the bit you're referring to) in your commit, but there's also the title of [G12](https://github.com/Ipstenu/wporg-plugin-guidelines/blob/b770a8e0b132006ed8dd171205a4f214f6050827/guideline-12.md) (including the link from the [`README.md`](https://github.com/Ipstenu/wporg-plugin-guidelines/blob/b770a8e0b132006ed8dd171205a4f214f6050827/README.md)).
