### ISSUE TITLE
readme.txt guidelines

### ISSUE THREAD

**Issue by rheinardkorf** [Ipstenu/wporg-plugin-guidelines#22]
I noticed new behaviour for `readme.txt` in the new plugin directory.

I love for instance how the FAQ section works, but would like to see some guidelines for what in the readme maps to which parts in the new directory.

**Comment by Ipstenu** [comment]
That is not related to this part of the project. You're not asking about Developer Guidelines, you're asking about https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/#how-the-readme-is-parsed
