### ISSUE TITLE
12 - affiliate links

### ISSUE THREAD

**Issue by ovann86** [Ipstenu/wporg-plugin-guidelines#23]
I'm concerned about the changes to item 12 regarding affiliate links.

The current guidelines state

> The plugin page (aka the readme.txt file) may not have “sponsored” links on it. Same goes for the translation files and any other linkback type schemes that will have content displayed on WordPress.org. Affiliate links are to be avoided. If they are included on settings pages, they must be disclosed.

which after discussing with the WP plugin team, was explained to mean they're allowed as long as they're not obscured through redirect links.

The proposed change would mean affiliate links are not allowed in the plugin page (aka the readme.txt file) at all.

> **Public facing pages on WordPress.org may not contain “sponsored” or “affiliate” links or third party advertisements.**
> Public facing pages includes the readmes and translation files. If such links are included on settings pages, they must be disclosed.

Affiliate links are a very small way that developers that contribute their work/time/resources to the directory can receive some return to cover operational costs.

I currently use affiliate links in my plugin pages and use the funds to run a demo website.

I'm concerned that this will make contribution less viable for developers.

I'm proposing that on-topic affiliate links should be allowed as long as they're not obscured. E.g. a plugin that extends a premium plugin can use an affiliate link to identify the premium plugin and refer users to the website if they choose to click it.

I agree that 'sponored' links (e.g. this update was sponsored by ...) should not be allowed.

**Comment by Ipstenu** [comment]
The decision to not permit affiliate links is because we don't want people to seo spam readmes and devalue WordPress.org. It's also not new. 

An affiliate link to "this is the theme you need for this plugin" is different from an advertisement.

Affiliate links to required products, when properly disclosed and obvious, can be an exception. Affiliate links to tucows because they translated the plugin is not permitted.

Does that help?

**Comment by joshuadavidnelson** [comment]
Just to be clear here, we're alright with affiliate links in the proper context, but this policy is more for advertisements/spam in readmes. Further, any affiliate links should be listed as such and only provided if they make sense (like a plugin dependent on a premium plugin).

So, for instance, if I develop a plugin that extends a premium plugin. I can place an affiliate link in the readme like: 

> "Notice: This plugin requires [Premium Plugin](http://premium.plugin/?ref=myafflidateid) (affiliate link)" 

but not like:

> "Notice: This plugin requires [Premium Plugin](http://customredirectedaffliatelink.com)"

Note the URL is different as well as the affiliate notice in those examples. Direct affiliate links are okay, but redirected links are not?

I agree with @ovann86 that affiliate links in readmes in the proper context are important. And I agree that advertisements/spam should not be in the repo (or the admin!).

**Comment by Ipstenu** [comment]
Link 1 is `http://premium.plugin/?ref=myafflidateid` and link two is `http://customredirectedaffliatelink.com/`

Redirected links should be avoided because I, as a user, cannot tell where you're sending me without clicking. Cloaked links (which is what a redirect is) are bad.

Direct affiliate links to directly _required_ products can be used within reason. If you link 18 or 30 times to, say, each an every one of Genesis' themes, you're stuffing, and that's bad.

> Public facing pages, including readmes and translation files, may not contain affiliate or sponsored links. Directly required products (such as themes or other plugins required for the plugin's use), are permitted within moderation. Links may also included on the WordPress Admin settings pages for the specific plugin. In all cases, affiliate links must be disclosed and must directly link to the affiliate service, not a redirect or cloaked URL.

**Comment by joshuadavidnelson** [comment]
Awesome, @Ipstenu, that's exactly the clarity I was hoping for - thanks for the response. In terms of affiliate links, these are the guidelines I use whenever I link to an affiliate url (anywhere), but I wanted to be sure we're all on the same page. 

Thanks for the work on these guidelines! I really appreciate putting it on GitHub for open comment.

**Comment by ovann86** [comment]
Thanks @joshuadavidnelson & @Ipstenu - I'm happy with the clarification and thanks for the opportunity for input.
