### ISSUE TITLE
14 - frequent commits

### ISSUE THREAD

**Issue by anastis** [Ipstenu/wporg-plugin-guidelines#25]
I feel that guideline 14 (along with its title) creates some confusion regarding the proper use of the repository. I know it got me confused at least.

Let me elaborate:
- **Frequent commits can be seen as gaming the Recently Updated lists**  - This suggests that the plugin repo should not be used for development, as commits may be small and frequent, during a normal development course.
- **Commits that only tweak minor aspects of the readme cause undue strain on the system** - Perhaps this needs to clarify *which* readme.txt it refers to, e.g. the *active* readme in case a Stable Tag field is defined. Example: As it stands, I'd be afraid to modify my trunk/readme.txt file's description (which points to a stable tag), in fear of getting punished. According to [How your readme.txt Works](https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/) though, it's suggested that the edit would be ignored.
- **Only commit code that is ready for deployment.** - Again, this suggests that the repo shouldn't be used for development.

I really don't know what would be good phrasing for the points above to become clearer. Perhaps they're fine as is, but a list of do's and dont's could help clarify things. 
At the very least, I feel there should be a bold statement on whether the repo is to be used for development or for deployment only.

**Comment by Ipstenu** [comment]
* That is accurate. The svn repo is not for development, it is a release repository.
* All readmes actually.
* Again, correct.

That sounds like, to me, you did understand it, you were just surprised by it.

**Comment by anastis** [comment]
I'm not really surprized. I was suspecting this is the case, however I couldn't verify it from any of the current sources.
I'd say, this piece of information, i.e. "The svn repo is not for development, it is a release repository" is not easily obtainable and it should be somehow mentioned in the guidelines. 
I mean, a first time plugin commiter, reading these guidelines (or the ones currently in place), will not know he's not supposed to use the repo for development.
All I'm suggesting is to make this clearer :)

**Comment by Ipstenu** [comment]
That sentence used to be there... Heh. I'll put that back in!
