### ISSUE TITLE
The term "Serviceware" is not widely used

### ISSUE THREAD

**Issue by dmccan** [Ipstenu/wporg-plugin-guidelines#26]
Item six, "Serviceware is permitted in the directory" -- the term Serviceware is not well known.  The explanation is clear.

Perhaps "Providing an interface to an external third party service is allowed."

**Comment by Ipstenu** [comment]
What about "software as a service"?

**Comment by dmccan** [comment]
Good!

**Comment by mrwweb** [comment]
+1 for this change. The guideline title in `readme.md` still says "Serviceware."
