### ISSUE TITLE
Perhaps change "blackmailing" to "pressuring"

### ISSUE THREAD

**Issue by dmccan** [Ipstenu/wporg-plugin-guidelines#27]
In item 9 - there is he bullet point "Compensating, misleading, or blackmailing users for reviews".  Pressuring might be a better word than blackmailing.  The definition of blackmail:

Demanding money from a person in return for not revealing compromising or injurious information about that person.

**Comment by Ipstenu** [comment]
What would you say if I told you that is exactly what we mean?

**Comment by Ipstenu** [comment]
My comment when it happened was quite colorful :/

I wouldn't be opposed to saying "Compensating, misleading, pressuring, extorting, or blackmailing...." Those are, tragically, all things that have happened. (Someone refused a refund until a review was changed to 4 stars.)

**Comment by dmccan** [comment]
That's sad.  I think your wording is fine, especially if you feel it is important to spell it out.  If you want to go shorter, pressuring encompasses extorting and blackmailing, but those do not necessarily cover the lesser pressuring.
