### ISSUE TITLE
11 - Admin messages

### ISSUE THREAD

**Issue by dartiss** [Ipstenu/wporg-plugin-guidelines#30]
One of my plugins detects for a clash with another plugin (a known issue). Something has to be actioned for it to work properly - for this reason I don't have a dismissible option on the admin message that I put out. Is this acceptable and, if so, I wonder if this section could be tweaked to accommodate such a scenario?

**Comment by Ipstenu** [comment]
Does the message go away if the action is successful? That is, if the alert says "You have to enable pretty permalink!" will it go away when I do so? That's fine. It _is_ dismissible, just via a specific action and not a click to dismiss.

**Comment by dartiss** [comment]
Yes it does so, yea, it meets your criteria. Do you think that needs a change to the wording or is it sufficient as is? Personally, I think it could probably do with making a little clearer.

**Comment by Ipstenu** [comment]
How about...

>  Error messages and alerts should include information on how to resolve the situation, and remove themselves when corrected.

Also changes 'issue' to 'situation' to be less pejorative 😄

**Comment by dartiss** [comment]
Yes, that's excellent - thanks Mika. Apologies for not responding earlier - bed and the lack of Git access at work!
