### ISSUE TITLE
Instructions - include network use case

### ISSUE THREAD

**Issue by valuser** [Ipstenu/wporg-plugin-guidelines#32]
If the plugin author includes instructions for the plugins use the author might consider including instructions for a network install use case.

An example of an plugin author/developer who currently follows this practice is imath.

**Comment by Ipstenu** [comment]
How is this a guideline, though? That sounds more like a documentation issue, which is not going to be covered by this specific project.

**Comment by valuser** [comment]
True. Agreed.

Sent by Val

**Comment by Ipstenu** [comment]
Okay, closing :) You should check out https://developer.wordpress.org/plugins/ - I think that would be the best place for it.
