### ISSUE TITLE
12. Public facing pages on WordPress.org may not contain “sponsored” or “affiliate” links or third party advertisements.

### ISSUE THREAD

**Issue by mrwweb** [Ipstenu/wporg-plugin-guidelines#37]
I have been in at least once situation—as I suspect others have—where a person or company has sponsored the development of a specific feature for a plugin.

It may just be the nomenclature that's tripping me up, but I'm unsure if crediting that person/company with a link in a changelog and/or on the front plugin page would violate this guidelines. I'm 70% sure it would?

**Comment by Ipstenu** [comment]
We don't want the readmes to be billboards. So if your plugin is sponsored by a dozen people/companies and you list all of them in your readme as 'thanks', then yes, that is a violation.

This is different from a props linking back to someone who helped you debug. We don't want sponsored links on the readme. So ... yes, in your example it would.

**Comment by mrwweb** [comment]
Thanks for the clarification. It would appear that this practice is [fairly wide spread](https://www.google.com/search?q=site%3Awordpress.org%2Fplugins%2F%20"sponsored%20by") given a cursory Google search. I can't quite decide if I think this guideline needs clarification. I think my only confusion was whether sponsoring development of a specific feature differed from advertising. While in my experience, the desire for the feature was the clear driving force (not promotion), I can see why the distinction is unenforceable. Separately, I've also been approached multiple times about linking to someone's site in exchange for a translation file (though this should now be less of an issue, yay language packs!).

So, this is rough, but maybe something like:

> Public facing pages, including readmes and translation files, may not contain affiliate or sponsored links, including links to "sponsors" of development or translations.

Maybe that's too specific, but on first read, I was left wondering.

**Comment by Ipstenu** [comment]
> Separately, I've also been approached multiple times about linking to someone's site in exchange for a translation file (though this should now be less of an issue, yay language packs!).

Perhaps ironically that's the _exact_ reason this rule came about in the first place 😦 There was a company who was getting people to do that in order to beef up their SEO.

Like many of our guidelines, it's ipso post facto enforceable. If we catch you at it, we warn you. If you keep on doing it, we close you. We're working on more tools, but at least you can't say you weren't warned unless you want to admit you didn't read the guidelines you agreed to 😉 

And yes, in the Directory Upgrade you'll be more clearly accepting these guidelines.

**Comment by mrwweb** [comment]
This all makes sense. I still might include that extra detail I proposed, but I can see that it's not technically needed.

The only other thing I thought of that might be worth clarifying is "props" links that I often see in changelogs. I could see a policy where those are allowed as links only to profiles.wordpress.org pages, but that gets awfully prescriptive...

**Comment by Ipstenu** [comment]
I think we'll 'assume good faith' on props for now :) If people start abusing that, we can always revisit.
