### ISSUE TITLE
Software As A Service - 3rd Party "requirement"

### ISSUE THREAD

**Issue by gsexton** [Ipstenu/wporg-plugin-guidelines#40]
This section states:

_Plugins that act as an interface to some external third party service (e.g. a video hosting site) ..._ 

It seems as though it could be simplified to:

_Plugins that act as an interface to some external service (e.g. a video hosting site) ..._ 

The inclusion of "third party" seems to imply that a service provider could not create a plugin for their own service. For example, EventBrite, or BrownPaperTicket.

**Comment by Ipstenu** [comment]
EventBrite is the 3rd party. User is party 1, WP is 2, Service is 3.
