### ISSUE TITLE
Reviews

### ISSUE THREAD

**Issue by braddalton** [Ipstenu/wporg-plugin-guidelines#44]
Where's the info about reviews in [reference to this post](https://wptavern.com/wordpress-plugin-team-revamps-guidelines-invites-feedback-on-github)?  Also, one problem i see is users submitting low ratings because they don't like the fact they sometimes have to pay for an upgrade or using bullying tactics to try and pressure plugin devs to provide free modification of plugins.

**Comment by Ipstenu** [comment]
I didn't write (nor was I even asked about) that WPTav post, so I can't possibly be expected to read their minds :)

However at a guess they're talking about this - https://github.com/Ipstenu/wporg-plugin-guidelines/blob/master/guideline-09.md - which has an example of "Creating accounts to generate fake reviews or support tickets (i.e. sockpuppeting)" 

Other than that, you'll have to be a little more specific in your question about the guidelines. Like what 'info' are you looking for? Is there a guideline you feel is unclear? Something we can make better?

Issues of users bullying developers has no place in the Plugin Guidelines, that would belong in the forum guidelines. These are _only_ intended to be for Plugin Devs who want to have their plugins hosted here, so we're not attempting to address users.

**Comment by braddalton** [comment]
Ok got it.
