### ISSUE TITLE
guideline-07.md - is getting info from an external site falls into the Phone Home?

### ISSUE THREAD

**Issue by tivnet** [Ipstenu/wporg-plugin-guidelines#53]
Example:

I have a free plugin in the .org repository and add-ons sold through my website.

If my free plugin is calling my website to get the list of add-ons available and displays it on the "About My Plugin" page - is that a "phone home"?

The guideline is talking about *submitting* information, so it's not clear if *getting* information is covered.

**Comment by tivnet** [comment]
@Ipstenu I am sure you know the answer. Thank you!

**Comment by Ipstenu** [comment]
This is not what this repo is for.

You should EMAIL plugins@wordpress.org if you have specific questions about specific plugins.

> If my free plugin is calling my website to get the list of add-ons available and displays it on the "About My Plugin" page - is that a "phone home"?

Yes. Are you contacting your server? Does your server have the ability to TRACK anyone who contacts it (especially a specific page)? Have idiots already used that to track users? You bet.

No tracking. Email plugins@wordpress.org if you have further questions.
