### ISSUE TITLE
Sponsor/Ad/Affiliate Banners in the Dashboard

### ISSUE THREAD

**Issue by jb510** [Ipstenu/wporg-plugin-guidelines#54]
I thought this came up in the discussions previously, not finding the history though.

There appears to still be no prohibition of what a plugin does in the ADMIN in terms of sponsor/affiliate banners beyond "no phoning home".

I think most people feel sponsor/ad banners and links on a plugins dedicated settings pages are reasonable, but take exception to plugins that display banner/links elsewhere in the admin.  

I think most people feel the dashboard is fair territory since the "public" doesn't see it, it only affect the site owner and if the site owner doesn't like it they can change plugins.  The problem with that though is on a lot of multi-author and membership type sites there are a lot of people in the dashboard that are _not_ the admin/site owner who sometimes do see those.

Would it be practical to include that prohibition on these on the backend for non-admin viewers or is that just too complicated and messy? ...or am I parsing "public" to narrowly to mean non-logged in?

**Comment by Ipstenu** [comment]
1) No phoning home _includes_ no remote loading banner images

2) This should be covered by what we mean in "11. The plugin should not hijack the admin dashboard." which actually says this:

> Upgrade prompts, notices, and alerts should be limited in scope and used sparingly or only on the plugin’s setting page. Any site wide notices or embedded dashboard widgets must be dismissible. Error messages and alerts should include information on how to resolve the situation, and remove themselves when completed.
> 
> Advertising within the WordPress Dashboard should be avoided. While developers are permitted to promote their own products and services, historically they have been ineffective; ideally users rarely visit these screens. Remember: tracking referrals via those ads is not permitted (see guideline 7) and most third-party systems do not permit back-end advertisements (notably, Google). Abusing the guidelines of an advertising system will result in such actions being reported.

The only thing missing might be saying "While developers are permitted to promote their own products and services _on their plugins' individual dashboards_ ..."

**Comment by jb510** [comment]
Ah! I missed that second paragraph. 

Still wondering if it makes sense to further restrict such advertising to admin user roles.

**Comment by Ipstenu** [comment]
Oh hey, go me, first sentence says "or only on the plugin’s setting page"

Since the setting page is restricted for security, for the most part I think we'll be covered. Alerts etc should also be restricted by user roles to prevent non-admins from knowing you don't upgrade or fix things promptly (which is a security hole if you allow open registration anyway....).

If your ads are all over every page of the dashboard, you'll get a nasty-gram from us about being annoying :) If you make your settings page a billboard that people hate, they'll leave you one-star reviews. Karma. Love it.
