### ISSUE TITLE
Clarification needed: Are action links allowed to contain social media links?

### ISSUE THREAD

**Issue by Zodiac1978** [Ipstenu/wporg-plugin-guidelines#72]
I see in  rule 11 this paragraph:
> Developers are welcome and encouraged to include links to their own sites or social networks, as well as locally (within the plugin) including images to enhance that experience.

But on which places are those social media images/links allowed? I don't think the plugin action links are a good fit:
![Bildschirmfoto 2020-10-13 um 00 42 25](https://user-images.githubusercontent.com/870475/95797643-47ba2d00-0cf0-11eb-84e2-a0accc38ff21.png)

**Comment by Ipstenu** [comment]
As long as the images are local, yes.

**Comment by Ipstenu** [comment]
FYI, you really would get a better response emailing plugins@wordpress.org about these sorts of things :)
