### ISSUE TITLE
Disallow animated plugin icons

### ISSUE THREAD

**Issue by mondalaci** [Ipstenu/wporg-plugin-guidelines#78]
If I may propose, animated plugin icons should be disallowed. See [this discussion](https://wordpress.org/support/topic/animated-plugin-icon-is-distracting/) for the rationale.

**Comment by Ipstenu** [comment]
While we don't disagree, this should be handled via code and not trying to micromanage people - https://meta.trac.wordpress.org/ticket/5464

We don't want to make more guidelines that can only be enforced by "catch 'em when we see 'em" as that is simply not sustainable.
