### ISSUE TITLE
Uglify to be avoided?

### ISSUE THREAD

**Issue by JDGrimes** [Ipstenu/wporg-plugin-guidelines#8]
In the section on [human readable code](https://github.com/Ipstenu/wporg-plugin-guidelines/blob/master/guideline-04.md):

>Using p,a,c,k,e,r or uglify is to be avoided.

WordPress core uses uglify to minify its JS files, so I've always intended to imitate that in plugins. Is there a reason that I shouldn't? Is WordPress just using uglify to provide minified versions of files for back-compat? I've always thought that providing minified scripts and styles was best-practice.

**Comment by Ipstenu** [comment]
Avoided in the context of the guideline. The only time WordPress core ever had anything that would have been considered a violation to this was the old easter egg that did the matrix joke. Compressing is fine, but using packer to make it a seemingly meaningless string of random things is not. Any way to clarify that without getting super wordy is welcome.

**Comment by dancameron** [comment]
I recommend using "obfuscation", I don't think it's too of a complex word for developers.

**Comment by Ipstenu** [comment]
I'd _been_ using obfuscation and got a lot of ESL folks confused (it now says 'obscured'). But I have an idea...

**Comment by Ipstenu** [comment]
Okay, check out the above pull request. Does that work better?

**Comment by pattonwebz** [comment]
I use uglify to combine and minify files and I'm also of the mindset that  doing so is best-practice that should be followed for performance reasons.

The option name given by uglify used to change variable/function names - which makes it unreadable - is called `mangle`. Perhaps stating something like - 'the use of uglify to combine and minify is fine however `mangle` should not be used'.

Something explicitly stating the `mangle` option is what is being forbidden would be better. I'm not aware of the option name in `p.a.c.k.e.r` but I expect it'd be best to explicitly list that too in a similar way. I feel that's the l only way to make this non-ambiguous and avoid confusion.

Another thing that may be worth considering (and maybe it's best to make my own issue to discuss this) is encouraging the inclusion of sourcemaps for compressed files.

**Comment by pattonwebz** [comment]
Just checked and `p.a.c.k.e r` uses 'obfuscuate' as the name given to the option which makes it non-human readable. Also setting it to 'best' will either minify it obfuscuate depending on which creates the best (smallest file) result. That would also need touched on probably.

If both systems are to be mentioned, by name, then I feel that it must be clarified which options are to be discouraged. One possible solution would be to not mention any specific system by name and instead 'must be human-readable' could be expanded in a way that gives it more clarity - because when I read the guideline (both it and the commit linked here) what is deemed 'human readable' isn't actually clear to me.

**Comment by Ipstenu** [comment]
Awesome, okay, then we can say for example that using the obfuscate feature of packer, and the mangle feature of uglify are to be avoided! Thank you @pattonwebz !!!

**Comment by pattonwebz** [comment]
Yep that works for me :)

If something were also included to state that 'other systems that use similar techniques to those should also be avoided' would also help cover any other systems that obfuscuate the code in a similar way - although mention of that may not be needed.
