### ISSUE TITLE
Continue on: "Are unreasonable technical code reviews expected?“

### ISSUE THREAD

**Issue by clivezhg** [Ipstenu/wporg-plugin-guidelines#80]
The last thread: https://github.com/WordPress/wporg-plugin-guidelines/issues/79.
 @Ipstenu, since you locked this thread eagerly, I believe you are also the last reviewer.
Becasue you said "You are intentionally opening the door for higher risk in your plugin and refusing to consider you could be wrong" in an earlier email (can we call it "insultation", or "PUA"?), I have been thinking the reviewer is someone else.
However, you never found a real least security issue, you even said something like "no one will read your code", so your points were basically driven by machine scanning.
According to my investigation, most of the hosted plugins are violating your code guidelines, more or less. So, if you are really concerning security as you stated, you should make them re-coding, too.
We think that your review manner should be known by more developers, because most developers expect reasonable code reviews, if they know unreasonable code reviews might be imposed, they might hesitate to submit a plugin, so avoid of wasting time of both sides.

(If you do find real security issue according to your points, as you stated "the security issues are real", you can create issues in my project: https://github.com/clivezhg/Unreasonable-Code-Reviews/. Otherwise, your statement is very pale)

**Comment by Ipstenu** [comment]
@clivezhg I don't know how to make this more clear for you: This is not a matter of guidelines.

Your issue is with the content of your code review. That's all.

I'm closing this again, because this GitHub repo is literally **ONLY FOR THE GUIDELINES**. Seriously man, you're in the wrong place.
