### ISSUE TITLE
The Unreasonable Code Review Issue Unsettled

### ISSUE THREAD

**Issue by clivezhg** [Ipstenu/wporg-plugin-guidelines#87]
@Ipstenu, you still don't provide a rational explanation on the closing of Wordpress plugin More-Lang:
https://github.com/WordPress/wporg-plugin-guidelines/issues/79 ,
https://github.com/WordPress/wporg-plugin-guidelines/issues/80 .

We think most developers are interested in your review motivations, because most of the hosted plugins are violating your code guideliines (as far as my investigations, every hosted plugin are violating). And you were unable to find a least real security issue in More-Lang, only raising issues based on guideline-violation (through machine scanning).

Your motivation to close More-Lang is still a riddle. Might it be racial discrimination? Or just a bad mood? Or district hatred? Anyway, most developers should be interested, because it's related to their welfare.

And Opensourcing is so great in our opionion, that many naive developers tend to believe that you should be fair. We keep warning of unexpected Unreasonable Code Review to avoid naive developers' loss.

You labelled the issues as "invalid" and closed them, and said "because this GitHub repo is literally ONLY FOR THE GUIDELINES. Seriously man, you're in the wrong place", then where is the right place? If you were unable to provide a proper place, we think here is a feasible place.

(BTW, MS has acquired Github, since Wordpress is the biggest competitor to MS' Web tech, we think here is not a right place for you to impose your tyranny, as you do in your Wordpress place. )

**Comment by clivezhg** [comment]
And my Wordpress account was disabled, the team might have done it to prevent me from saying anything, so here is a good place to discuss.

**Comment by chriscct7** [comment]
Mika doesn't work on, nor has in a while, on any of the plugin reviews. 

> then where is the right place?

The proper and **only place** to discuss issues related to a specific plugin is in the email you received from plugins@wordpress.org. 

All plugins are treated the same way.

Multiple plugin team members have reviewed the report for your plugin, and all have agreed the issues raised are all valid. If you want the plugin to be re-listed, you need to fix the issues addressed in the email.
