### ISSUE TITLE
Guideline 18 Broken

### ISSUE THREAD

**Issue by 88Navistar** [Ipstenu/wporg-plugin-guidelines#93]
The last line should be removed:
**In return, we promise to use those rights sparingly and with as much respect as possible for both end users and developers.**

18. We reserve the right to maintain the Plugin Directory to the best of our ability.
Our intent is to enforce these guidelines with as much fairness as humanly possible. We do this to ensure overall plugin quality and the safety of their users. To that end, we reserve the following rights:

... to update these guidelines at any time.
... to disable or remove any plugin from the directory, even for reasons not explicitly covered by the guidelines.
... to grant exceptions and allow developers time to address issues, even security related.
... to remove developer access to a plugin in lieu of a new, active, developer.
... to make changes to a plugin, without developer consent, in the interest of public safety.
In return, we promise to use those rights sparingly and with as much respect as possible for both end users and developers.

**Comment by loadstring1** [comment]
true 👍
